# 1️⃣ Indexing in NumPy

- Indexing = accessing a single element from an array

## 🔹 1D Array Indexing
# ✅ Syntax
- arr[index]

In [4]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[3])

40


## 🔹 2D Array Indexing
# ✅ Syntax
- array[row_index, column_index]

In [5]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[0, 1])  
print(arr2d[2, 2])   


2
9


## 🔹 3D Array Indexing
# ✅ Syntax
- array[layer, row, column]

In [ ]:
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(arr3d[1, 0, 1])   


6


## 2️⃣ Slicing in NumPy
- Slicing means accessing multiple elements at once.

## 🔹 1D Array Slicing
# ✅ Syntax
- array[start : stop : step]

# Explanation
- start → where to begin
- stop  → where to stop
- step  → how many items to skip

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])     
print(arr[:3])      
print(arr[3:])      
print(arr[::2])     


[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]


## 🔹 2D Array Slicing
# ✅ Syntax
- array[row_start:row_end , col_start:col_end]

In [13]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[:2, :2])

[[1 2]
 [4 5]]


# 🔹 Row and Column Slicing
## Entire Row
- array[row_index, :]

## Entire Column
- array[:, column_index]

In [ ]:
print(arr2d[1, :])   
print(arr2d[:, 2])  

[4 5 6]
[3 6 9]


# 3️⃣ Boolean Indexing
### ✅ Syntax
- array[condition]

In [15]:
arr = np.array([10, 25, 30, 15, 40])

print(arr[arr > 20])  

[25 30 40]


# 4️⃣ Fancy Indexing
- Selecting Multiple element at once

## ✅ Syntax
- array[[index1, index2, index3]]

In [16]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])   

[10 30 50]
