# import NumPy

In [2]:
import numpy as np

## Create Array

# Question Solve

### 🔹 PART 1: 1D Array Indexing (1–20)

1. Create a 1D NumPy array of 10 elements and print the first element

In [36]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [24]:
print(arr[1])

1


2. Print the last element using negative indexing

In [26]:
print(arr[-1])

10


3. Print the 3rd element of an array

In [27]:
print(arr[3])

3


4. Access the middle element of an array

In [28]:
print(arr[len(arr) // 2])

5


5. Replace the first element with 100

In [29]:
arr[0] = 100
print(arr)

[100   1   2   3   4   5   6   7   8   9  10]


6. Replace the last element with 0

In [30]:
arr[-1] = 0
print(arr)

[100   1   2   3   4   5   6   7   8   9   0]


7. Print all elements except the first

In [31]:
print(arr[1:])

[1 2 3 4 5 6 7 8 9 0]


8. Print all elements except the last

In [32]:
print(arr[:-1])

[100   1   2   3   4   5   6   7   8   9]


9. Access elements using negative indices

In [33]:
print(arr[-1])

0


10. Count total elements using indexing logic

In [39]:
print(len(arr))

11


Use Loop

In [41]:
count = 0
for i in range(10000000):
    try:
        _ = arr[i]
        count += 1
    except IndexError:
        break
print("Total Element", count)        

Total Element 11


11. Print even index elements

In [37]:
print(arr[::2])

[ 0  2  4  6  8 10]


12. Print odd index elements

In [34]:
print(arr[1::2])

[1 3 5 7 9]


13. Access every second element

In [43]:
print(arr[::2])

[ 0  2  4  6  8 10]


# Use loop

In [45]:
for i in range(0, len(arr), 2):
    print(arr[i], end=" ")


0 2 4 6 8 10 

14. Access every third element

In [46]:
for i in range(0, len(arr), 3):
    print(arr[i], end=" ")

0 3 6 9 

15. Reverse an array using slicing

In [47]:
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1  0]


16. Check if slicing changes the original array

17. Copy sliced array and modify it

18. Extract first 5 elements

19. Extract last 5 elements

20. Extract alternate elements from end to start

# 🔹 PART 2: 1D Array Slicing (21–35)

21. Slice array from index 2 to 6

22. Slice first half of the array

23. Slice second half of the array

24. Slice array excluding first and last element

25. Slice using step = 2

26. Slice using step = -1

27. Slice from index 5 to 1 (reverse)

28. Slice array into two equal parts

29. Slice array without start index

30. Slice array without stop index

31. Slice array using only step

32. Create a view and modify it

33. Create a copy using slicing

34. Compare view vs copy

35. Slice array using variable indices

# 🔹 PART 3: 2D Array Indexing (36–55)

36. Create a 3×3 array and access element at (0,0)

In [60]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr[0, 0])

[1 2 3]


37. Access element at last row last column

In [63]:
print(arr[-1, -1])

[7 8 9]


38. Access center element

39. Access first row

40. Access last row

41. Access first column

42. Access last column

43. Access element using negative indexing

44. Replace element at (1,1) with 99

45. Access second row third column

46. Access all elements of a specific row

47. Access all elements of a specific column

48. Access diagonal element manually

49. Access top-right element

50. Access bottom-left element

51. Count rows using indexing

52. Count columns using indexing

53. Access multiple elements using index list

54. Modify one full row

55. Modify one full column

# 🔹 PART 4: 2D Array Slicing (56–75)

56. Slice first two rows

57. Slice last two rows

58. Slice first two columns

59. Slice last two columns

60. Extract a 2×2 sub-matrix from top-left

61. Extract a 2×2 sub-matrix from bottom-right

62. Slice middle row only

63. Slice middle column only

64. Slice alternate rows

65. Slice alternate columns

66. Slice rows with step 2

67. Slice columns with step 2

68. Reverse rows of matrix

69. Reverse columns of matrix

70. Reverse entire matrix

71. Slice matrix excluding border

72. Replace sliced part with zeros

73. Check if slicing affects original matrix

74. Copy slice and modify it

75. Convert slice to 1D array

# 🔹 PART 5: Boolean Indexing (76–90)

76. Select elements greater than 10

77. Select elements less than 5

78. Select even numbers

79. Select odd numbers

80. Replace values > 50 with 0

81. Count elements satisfying a condition

82. Select elements between 10 and 30

83. Apply condition on 2D array

84. Replace negative values with 0

85. Select rows where value > threshold

86. Boolean indexing on columns

87. Combine two conditions using

88. Combine two conditions using

89. Use np.where with indexing

90. Boolean mask and slicing together

# 🔹 PART 6: Fancy Indexing (91–100)

91. Access elements using index list

92. Access multiple rows using fancy indexing

93. Access multiple columns using fancy indexing

94. Change values at specific indices

95. Extract random elements using index array

96. Access diagonal using fancy indexing

97. Select rows in custom order

98. Select columns in custom order

99. Combine fancy + boolean indexing

100. Difference between fancy indexing and slicing (code example)