In [7]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10, 11, 12])

# ➡️ Manipulation in NumPy
- Modifying the structure, order, shape, or elements of a NumPy array.

## Operations Included in NumPy Manipulation

### 1️⃣ Reshape / Resize
- Change the shape or size of an array.


In [3]:
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 2️⃣ Flattening
- Convert a multi-dimensional array into a 1D array.

### returns a copy      

In [4]:
a.flatten() 

array([1, 2, 3, 4, 5, 6])

### returns a view (memory efficient)

In [5]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

## 3️⃣ Joining Arrays
- Combine multiple arrays into one

In [11]:
np.concatenate((a, b), axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
np.hstack((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## 4️⃣ Splitting Arrays
- Divide an array into multiple sub-arrays.

In [14]:
np.split(a, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

# 5️⃣Adding / Removing Elements

In [15]:
np.append(a, 10)

array([ 1,  2,  3,  4,  5,  6, 10])

In [16]:
np.insert(a, 1, 99)

array([ 1, 99,  2,  3,  4,  5,  6])

In [17]:
np.delete(a, 2)

array([1, 2, 4, 5, 6])

# 6️⃣ Changing Data Type

In [18]:
a.astype(float)

array([1., 2., 3., 4., 5., 6.])

# 7️⃣ Copy vs View
- Memory management in NumPy.

# creates a new array

In [19]:
a.copy()

array([1, 2, 3, 4, 5, 6])

# shares the same memory

In [20]:
a.view()

array([1, 2, 3, 4, 5, 6])