In [1]:
import numpy as np

In [2]:
a = [10, 20, 30, 40]
arr = np.array(a)
arr

array([10, 20, 30, 40])

In [4]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr = np.array((4,4))
arr

array([4, 4])

In [8]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
a = [[1,2,3],
     [4,5,6]]
arr = np.array(a)
arr.shape

(2, 3)

In [10]:
a = [1,2,3,4,5]
arr = np.array(a)
arr*2

array([ 2,  4,  6,  8, 10])

In [14]:
arr = np.arange(0, 21, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
a = [10, 20, 30, 40]
arr = np.array(a)
arr.mean()

np.float64(25.0)

In [18]:
a = [3, 7, 2, 9, 5]
arr = np.array(a)
arr.max()

np.int64(9)

In [20]:
a = [1,2,3,4,5,6] 
arr = np.array(a)
res = arr.reshape((2,3))
res

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a = [10,20,30,40,50]
arr = np.array(a)
res = arr[:3]
res

array([10, 20, 30])

In [23]:
a = [10, 50, 20, 40, 80, 70]
arr = np.array(a)
arr[arr>=50] = 0
arr

array([10,  0, 20, 40,  0,  0])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

rep = np.vstack((a, b))
print(rep)

[[1 2 3]
 [4 5 6]]


In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])

hst = np.hstack((a, b))
hst

array([1, 2, 3, 4, 5, 6])

In [28]:
a = np.arange(1,7)
res = a.reshape(2, 3)
req = res.sum(axis=1)
req

array([ 6, 15])

In [29]:
a = np.arange(1,7)
res = a.reshape(2, 3)
req = res.mean(axis=0)
req

array([2.5, 3.5, 4.5])

In [5]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(1,101,10)
arr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75], dtype=int32)

In [6]:
a = [10, 50, 20, 40]
arr = np.array(a)
res = np.sort(arr)[::-1]
res

array([50, 40, 20, 10])

In [7]:
a = [10, 50, 20, 40]
arr = np.array(a)
res = np.argmax(arr)
res

np.int64(1)

In [8]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

res = np.dot(A, B)
res

array([[19, 22],
       [43, 50]])

1. Create array of shape (5,5) with random integers and replace diagonal with 0

In [11]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(1, 10, (5,5))
np.fill_diagonal(arr, 0)
arr

array([[0, 4, 8, 5, 7],
       [3, 0, 8, 5, 4],
       [8, 8, 0, 6, 5],
       [2, 8, 6, 0, 5],
       [1, 6, 9, 1, 0]], dtype=int32)

2. Create matrix and compute eigenvalues (if possible)

In [6]:
arr = np.array([[1,2],
                [3,4]])

vals, vecs = np.linalg.eig(arr)

print(vals)

[-0.37228132  5.37228132]


3. Find elements common between two arrays

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

res = np.intersect1d(a, b)
res

array([3, 4])

4. Normalize an array (0–1 scaling)

In [14]:
a = [10, 20, 30, 40]
arr = np.array(a)
res = (arr - arr.min()) / (arr.max() - arr.min())
res

array([0.        , 0.33333333, 0.66666667, 1.        ])

5. Compute standard deviation of array

In [15]:
a = [10, 50, 20, 40]
arr = np.array(a)
res = np.std(arr)
res

np.float64(15.811388300841896)

6. Replace NaN values with 0

In [1]:
import numpy as np
a = [10, np.nan, 30, np.nan]
arr = np.array(a)
res = np.nan_to_num(arr)
res

array([10.,  0., 30.,  0.])

7. Perform broadcasting: add 1D array to 2D array

In [2]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

res = a + b
print(res)

[[11 22 33]
 [14 25 36]]


8. Find unique elements and counts

In [3]:
arr = np.array([1,2,2,3,3,3,4])

vals, counts = np.unique(arr, return_counts=True)

print(vals)
print(counts)

[1 2 3 4]
[1 2 3 1]


9. Flatten a 3×3 matrix

In [4]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

res = arr.flatten()
print(res)

[1 2 3 4 5 6 7 8 9]


10. Swap two rows in a matrix

In [5]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr[[0,2]] = arr[[2,0]]

print(arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# Reshaping

1. Create array 1 to 12 and reshape into (3,4)

In [7]:
arr = np.arange(1, 13)
res = arr.reshape(3, 4)
res

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2. Reshape [1,2,3,4,5,6] into (2,3)

In [10]:
a = [1,2,3,4,5,6] 
arr = np.array(a)
res = arr.reshape((2, 3))
res

array([[1, 2, 3],
       [4, 5, 6]])

3. Convert a 1D array of size 9 into (3,3)

In [11]:
arr = np.arange(9)
res = arr.reshape(3, 3)
res

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Flatten a 2D array [[1,2],[3,4]]

In [16]:
a = [[1,2],
     [3,4]]
arr = np.array(a)
res = arr.flatten()
print(res)

[1 2 3 4]


5. Reshape array 1 to 8 into (2,2,2)

In [19]:
arr = np.arange(1,9)
res = arr.reshape(2,2,2)
res

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

8. Create array and check .shape before and after reshape

In [22]:
arr = np.arange(1,7)
arr.shape
res = arr.reshape(2,3)
res.shape

(2, 3)

9. Convert (4,3) array into (3,4)

In [24]:
arr = np.arange(12).reshape(4,3)
print("Original shape:", arr.shape)
res = arr.reshape(3,4)
print("New shape:", res.shape)
print(res)

Original shape: (4, 3)
New shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
