# 🔄 Reshaping in NumPy
- changing the shape (dimensions) of a NumPy array without changing its data.

## 1️⃣ reshape()
- reshape() changes the number of rows and columns of an array while keeping all elements the same.

### 🧾 Syntax
- array.reshape(new_shape)
- array.reshape(rows, columns)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)

### 🧪 Example

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)


[[1 2 3]
 [4 5 6]]


# 2️⃣ Reshaping with -1
- Using -1 tells NumPy to automatically calculate one dimension based on the array size.

##🧾 Syntax
- array.reshape(-1, columns)
- array.reshape(rows, -1)


## 🧪 Example


In [3]:
arr.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

# 3️⃣ Reshaping to Higher Dimensions (3D)
- A 1D or 2D array can be reshaped into a 3D array, as long as the total number of elements matches.

## 🧾 Syntax
- array.reshape(dim1, dim2, dim3)

🧪 Example

In [4]:
arr.reshape(1, 2, 3)

array([[[1, 2, 3],
        [4, 5, 6]]])

# 4️⃣ View vs Copy in Reshaping
- reshape() usually returns a view of the original array
- Changes in the reshaped array may affect the original array

🧪 Example

In [6]:
b = arr.reshape(2, 3)
b[0, 0] = 99
print(b)

[[99  2  3]
 [ 4  5  6]]


# 5️⃣ resize() (Related to Reshaping)
- resize() changes the shape of the original array itself.
- If the new shape is larger, NumPy repeats elements.

## 🧾 Syntax
- array.resize(rows, columns)

🧪 Example

In [7]:
arr.resize(2, 3)

# Question Practice

## 🔹 Basic Level (1–15)

1. Create a 1D NumPy array of 6 elements and reshape it into a 2×3 array

2. Reshape a 1D array of 8 elements into a 4×2 array

3. Convert a 1D array of 9 elements into a 3×3 matrix

4. Reshape a 1D array into a 1×N array

5. Reshape a 1D array into an N×1 array

6. Check the shape of an array before reshaping

7. Print the shape of the array after reshaping

8. Try reshaping an array into an incompatible shape and observe the error

9. Reshape a 1D array of 12 elements into a 3×4 array

10. Convert a 2D array into a 1D array using reshape

11. Reshape a 2D array into another 2D shape with same elements

12. Reshape an array without storing it in a new variable

13. Check whether reshaping changes the original array

14. Print total number of elements before and after reshaping

15. Convert a 1D array into a square matrix

# 🔹 Using -1 in Reshape (16–25)

16. Reshape a 1D array of 10 elements using -1 for rows

Reshape a 1D array of 12 elements using -1 for columns

Convert a 1D array into a 2D array using one -1

Reshape an array into (-1, 2)

Reshape an array into (3, -1)

Try using -1 in more than one dimension (observe result)

Use -1 to reshape a 1D array into a column matrix

Reshape a 2D array into a 3D array using -1

Convert a 3D array back into a 2D array using reshape

Automatically reshape an array without manually calculating dimensions

# 🔹 Intermediate Level (26–40)

26. Reshape a 1D array of 24 elements into a 3×4×2 array

Reshape a 2D array into a 3D array

Convert a 3D array into a 1D array using reshape

Reshape an array and modify an element—check if original array changes

Store reshaped array in a variable and update values

Compare shape before and after reshaping

Use reshape inside a print statement

Reshape an array returned by np.arange()

Reshape an array created using np.linspace()

Reshape an array and apply indexing on it

Check memory sharing between original and reshaped array

Convert a row matrix into a column matrix using reshape

Flatten a reshaped array using reshape

Convert a reshaped array back to original shape

Reshape an array inside a function

# ✅ Advanced / Interview Level – ANSWERS (41–50)

41. Write a program to reshape an array based on user input

Check if reshaping creates a view or a copy

Compare reshape() and resize() with example

Use reshape for preparing data for machine learning

Convert feature array into (n_samples, n_features) format

Reshape image-like data into a 2D array

Handle reshaping error using try-except

Validate reshaping using .size attribute

Reshape array dynamically using variables

Write a program to reshape data without changing total elements all answer