In [1]:
import numpy as np

In [2]:
image = np.array([
    [10, 10, 10, 10, 10],
    [10, 50, 50, 50, 10],
    [10, 50,100, 50, 10],
    [10, 50, 50, 50, 10],
    [10, 10, 10, 10, 10]
])

In [3]:
kernel_x = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

In [4]:
kernel_y = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
])

In [8]:
def convolve(image, kernel):
    h, w = image.shape
    kh, kw = kernel.shape
    
    pad = kh // 2
    padded = np.pad(image, pad, mode='constant')
    
    output = np.zeros((h, w))
    
    for i in range(h):
        for j in range(w):
            region = padded[i:i+kh, j:j+kw]
            output[i, j] = np.sum(region * kernel)
    
    return output

In [9]:
edge_x = convolve(image, kernel_x)
edge_y = convolve(image, kernel_y)

# Combine both directions
edges = np.sqrt(edge_x**2 + edge_y**2)

print("Edges:\n", edges)

Edges:
 [[ 98.99494937 164.92422502 200.         164.92422502  98.99494937]
 [164.92422502 240.4163056  260.         240.4163056  164.92422502]
 [200.         260.           0.         260.         200.        ]
 [164.92422502 240.4163056  260.         240.4163056  164.92422502]
 [ 98.99494937 164.92422502 200.         164.92422502  98.99494937]]


In [11]:
edges = (edges / np.max(edges)) * 255
edges = edges.astype(np.uint8)

print("Final Edge Image:\n", edges)

Final Edge Image:
 [[ 97 161 196 161  97]
 [161 235 255 235 161]
 [196 255   0 255 196]
 [161 235 255 235 161]
 [ 97 161 196 161  97]]
