In [1]:
import numpy as np

1. Create a 1D array with numbers from 0 to 9.

In [2]:
arr = np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]


2. Create a 1D array with numbers from 10 to 20.

In [5]:
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


3. Convert the list [5, 10, 15, 20] into a Numpy array.

In [7]:
list = [5, 10, 15, 20]
arr = np.array(list)
print(arr)

[ 5 10 15 20]


4. Create a 1D array of 5 zeros.

In [10]:
a = np.zeros(5,)
print(a)

[0. 0. 0. 0. 0.]


5. Create a 1D array of 5 ones.

In [12]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


6. Create a 1D array of 10 evenly spaced numbers between 0 and 1.

In [ ]:
arr =  np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


7. Create a 1D array of 10 evenly spaced numbers between 1 and 5.

In [17]:
arr = np.linspace(1, 5, 10)
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


8. Create a 1D array of 5 random integers between 1 and 50.

In [28]:
arr = np.random.randint(1, 51, 5)
print(arr)

[13 41 21  4 46]


9. Create a 1D array of 5 random numbers between 0 and 1.

In [30]:
arr = np.random.rand(5)
print(arr)

[0.85514287 0.73858385 0.06127104 0.70093668 0.29590587]


10. Create a 1D array of numbers from 0 to 9 with a step of 2.

In [31]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


11. Create a 2x2 matrix of zeros.

In [32]:
arr = np.zeros((2, 2))
print(arr)

[[0. 0.]
 [0. 0.]]


12. Create a 3x3 matrix of ones.

In [33]:
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


13. Create a 4x4 identity matrix.

In [35]:
arr = np.eye(4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


14. Reshape 1D array [0,1,2,3,4,5,6,7,8] into 3x3 matrix.

In [36]:
arr = np.array([0,1,2,3,4,5,6,7,8])
matrix = arr.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


15. Create a 2x5 matrix using linspace() from 0 to 10.

In [37]:
arr = np.linspace(0, 10, 10)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 0.          1.11111111  2.22222222  3.33333333  4.44444444]
 [ 5.55555556  6.66666667  7.77777778  8.88888889 10.        ]]


16. Create a 1D array of 10 even numbers starting from 0.

In [39]:
arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


17. Create a 1D array of 10 odd numbers starting from 1.

In [40]:
arr = np.arange(1,21,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


18. Create a 3x3 matrix using arange() with numbers 0 to 8.

In [41]:
arr = np.arange(0, 9)
matrix = arr.reshape(3, 3)
print(arr)

[0 1 2 3 4 5 6 7 8]


19. Create a 3x2 matrix of random numbers between 0 and 1.

In [42]:
arr = np.random.rand(3, 2)
print(arr)

[[0.56347215 0.50941404]
 [0.63990693 0.88698418]
 [0.02504697 0.89785676]]


20. Create a 2x4 matrix with all elements as 7.

In [44]:
arr = np.full((2, 4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]]


21. Create a 3x3 matrix from list [[1,2,3],[4,5,6],[7,8,9]] using

In [45]:
list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list)
matrix = arr.reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 1️⃣ Array Creation

22. Create a 1D NumPy array with numbers from 1 to 10.

In [3]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


23. Create a 2x3 matrix of zeros.

In [5]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


24. Create a 3x3 matrix of ones.

In [6]:
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


25. Create a 4x4 identity matrix.

In [2]:
arr = np.eye(4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


26. Create a 1D array of numbers from 0 to 20 with step 2 using `arange()`.

In [3]:
arr = np.arange(0, 21, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


27. Create a 1D array of 5 numbers equally spaced between 0 and 1 using `linspace()`.

In [4]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


28. Create a 3x3 matrix filled with 7.

In [7]:
arr = np.full((3, 3), 7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


29. Convert a Python list `[1, 2, 3, 4]` into a NumPy array.

In [8]:
list = [1, 2, 3, 4]
arr = np.array(list)
print(arr)

[1 2 3 4]


30. Create a 2x3 matrix of random integers between 0 and 10.

In [3]:
arr = np.random.randint(0, 10, size=(2, 3))
print(arr)

[[4 2 0]
 [4 2 3]]


31. Create a 3x3x3 array of random numbers between 0 and 1.

In [4]:
arr = np.random.randint(0, 2, size=(3,3,3))
print(arr)

[[[1 0 1]
  [1 0 0]
  [1 0 1]]

 [[1 1 0]
  [1 1 1]
  [1 1 1]]

 [[0 0 1]
  [1 1 0]
  [1 1 0]]]


32. Create an array of shape (2,3) and reshape it to (3,2).

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original array:")
print(arr)

reshaped_arr = arr.reshape(3, 2)
print("Reshaped array:")
print(reshaped_arr)

Original array:
[[1 2 3]
 [4 5 6]]
Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


33. Create a 5x5 matrix with random values and extract the diagonal.

34. Create a 1D array with numbers from 1 to 9 and reshape it to 3x3.

35. Create a 4x4 matrix where all values are 0 except the border which is 1.

36. Create a 10x10 matrix with random values and find the max and min of the matrix.

# 2️⃣ Array Properties

37. Create a 1D NumPy array `[1,2,3,4]` and check its `shape`.

In [6]:
df = np.array([1, 2, 3, 4])
print(df.shape)

(4,)


38. Create a 2x3 array of zeros and check its `size`.

In [7]:
arr = np.zeros((2, 3))
print("Array of zeros:")
print(arr)

print("Size of the array:", arr.size)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Size of the array: 6


39. Create an array `[10,20,30]` and find its number of dimensions `(ndim)`.

In [8]:
arr = np.array([10, 20, 30])
print(arr.ndim)

1


40. Create an array `[1.0, 2.5, 3.7]` and check its data type `(dtype)`.

In [9]:
arr = np.array([1.0, 2.5, 3.7])
print(arr.dtype)

float64


41. Create a 3x3 array and print its `itemsize`.

In [10]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Item size:", arr.itemsize)

Item size: 8


42. Create an array `[1,2,3,4,5,6]` and `reshape` it into 2x3. Check its new shape.

In [14]:
arr = np.array([1,2,3,4,5,6])
print("Original array")
print(arr)

reshaped_arr = arr.reshape(2, 3)
print("Reshaped array:")
print(reshaped_arr)

Original array
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


43. Create a 4x4 random integer array and check total memory `(nbytes)`.

In [6]:
arr = np.random.randint(1, 10, size=(4, 4))
print(arr)
print("Total memory (in bytes):", arr.nbytes)

[[1 1 9 3]
 [8 7 5 7]
 [6 5 1 6]
 [7 3 3 2]]
Total memory (in bytes): 64


44. Create an array `[1,2,3,4]` of type `int32` and convert it to `float64`.

45. Create a 3x3 array and get its transpose using a property.

46. Create an array of 10 elements and check number of bytes per element and total bytes.

47. Create a 3x3x3 array and find its number of dimensions and shape.

48. Create a 2x4 array and flatten it to 1D. Check its shape before and after.

49. Create an array [1,2,3,4] and change its data type to complex.

50. Create a 5x5 identity matrix and check dtype, shape, size.

51. Create a 2x3 array of random numbers and check memory usage per element.

52. Create an array and check if it is C-contiguous.

53. Create a 2x3 array of integers and convert it to boolean type.

54. Create an array `[10,20,30,40]` and print number of elements, `shape`, `size`, `ndim`, `itemsize` in one go.

55. Create a 3x3 array and swap rows and columns using a property.

56. Create an array of 12 elements and reshape it to 2x2x3. Print its `shape`, `ndim`, `size`, `dtype`.

# 🟢 Broadcasting Questions

57. Create a 1D array [1, 2, 3] and add a scalar value 5 to it using broadcasting.

58. Add a 1D array [1, 2, 3] to a 2D array of shape (3, 3). Explain why broadcasting works.

59. Multiply a (3, 1) array with a (1, 4) array and find the resulting shape.

60. Subtract a 1D array of shape (3,) from a 2D array of shape (3, 3) using broadcasting.

61. Add a scalar to a 3D array of shape (2, 2, 2).

62. Add a column vector `(4,1)` to a row vector `(1,3)`. What will be the output shape?

63. Add a 1D array of shape `(3,)` to a 2D array of shape `(4,3)`.

64. Multiply a 2D array `(2,3) `with a 1D array `(3,)`.

65. Divide a `(3,3)` array by a `(3,)` array using broadcasting.

66. Add two arrays of shapes `(3,1)` and `(3,)`. Will broadcasting work? Why?

67. Explain why broadcasting fails when adding arrays of shapes `(3,2)` and `(3,)`.

68. Reshape a 1D array of shape `(4,)` so it can be broadcast with a `(4,3)` array.

69. Given arrays of shape `(2,3,4)` and `(4,)`, explain how broadcasting applies.

70. Add arrays of shapes `(5,1,3)` and `(1,4,3)`. What is the output shape?

71. Identify and fix a broadcasting error in a NumPy operation.

# 🔵 Vectorization Questions

72. Add two arrays [1,2,3,4] and [5,6,7,8] using vectorized operations.

73. Multiply all elements of an array by `10` without using loops.

74. Compute the square of each element in an array using vectorization.

75. Find the mean of an array using a vectorized NumPy function.

76. Compare two arrays element-wise and return a boolean array.

77. Replace all negative values in an array with `0` using vectorization.

78. Apply a condition to an array and extract elements greater than 50.

79. Compute `sin(x) + cos(x)` for each element of an array using vectorized functions.

80. Normalize an array using vectorized operations.

81. Perform element-wise multiplication between two 2D arrays.

82. Convert a loop-based array addition into a vectorized operation.

83. Apply different operations on even and odd elements using vectorization.

84. Use `where()` to perform conditional vectorized operations.

85. Explain why vectorized operations are faster than Python loops.

# 🔹 NumPy Indexing & Slicing 

# 🟢 Indexing

86. Create a 1D NumPy array [1, 2, 3, 4, 5] and access the element at index 0.

87. Access the element at index 3 from a 1D array.

88. Access the last element of an array using negative indexing.

89. Create a 2D array of shape (3,3) and access the element at row 1, column 2.

90. Access the entire first row of a 2D array.

91. Access the entire last row of a 2D array.

92. Access the entire first column of a 2D array.

93. Access the entire last column of a 2D array.

94. From a 1D array, access elements at indices [0, 2, 4].

95. Create a 3D array and access the element at index [0, 1, 1].

96. What does arr[-1] return in a 1D NumPy array?

97. Access the diagonal element at position (2,2) of a square matrix.

98. Access only elements greater than 10 using indexing.

99. Access the first element of the last row in a 2D array.

100. Access the second row and third column element using one statement.

101. What is returned when indexing a single element from a NumPy array?

102. Access all elements of a NumPy array using indexing.

103. Access elements using a boolean condition (arr > 5).

104. Access the middle element of an odd-length array.

105. Access the first element of a 3D array.

106. Access the last element of the last layer in a 3D array.

107. Access the entire second layer of a 3D array.

108. Access multiple rows using a list of indices.

109. Access the corner elements of a 2D array.

# 🔵 Slicing

110. Slice a 1D array to get elements from index 1 to 4.

111. Extract the first three elements of an array.

112. Slice an array to get elements from index 2 till the end.

113. Extract all elements except the last one.

114. Reverse a 1D NumPy array using slicing.

115. Extract every second element from a 1D array.

116. Slice a 2D array to get the first two rows.

117. Slice a 2D array to get the last two columns.

118. Extract a 2×2 sub-array from the top-left corner.

119. Slice rows 1 to 3 and columns 0 to 2.

120. Extract a 2×2 sub-array from the top-left corner.

121. Slice rows 1 to 3 and columns 0 to 2.

122. Extract all rows but columns from index 1 onward.

123. Slice a 2D array to reverse the order of rows.

124. Slice a 2D array to reverse the order of columns.

125. Slice a 3D array to get only the first layer.

126. Slice a 3D array to get the last layer.

127. Extract the middle row from a 2D array using slicing.

128. Extract the middle column from a 2D array using slicing.

129. Slice a 2D array using step size 2 for rows.

130. Slice a 2D array using step size 2 for columns.

131. Slice a 2D array using negative step.

132. Extract alternate rows and columns together.

134. Modify a sliced array and observe changes in the original array.

135. Create a copy of a sliced array so the original array is not affected.

136. What is the shape of the array obtained by slicing arr[1:4, 2:5]?

137. Explain the difference between slicing that returns a view and slicing that returns a copy.

# 🔹NumPy Reshaping & Manipulation

Create a 1D array of 12 elements and reshape it into a (3,4) array.

Reshape a (2,6) array into a (3,4) array.

Convert a 1D array of 9 elements into a (3,3) matrix.

Reshape a (4,3) array into a 1D array.

What happens if you try to reshape an array into an incompatible shape?

Use -1 to reshape a 1D array of 24 elements into 3 rows.

Convert a 2D array into a column vector.

Convert a 2D array into a row vector.

Flatten a 2D array using flatten().

Flatten a 2D array using ravel().

What is the difference between flatten() and ravel()?

Reshape a 3D array into a 2D array.

Change the shape of an array without changing its data.

Use reshape() to create a copy of an array.

Reshape an array to have one column and multiple rows.

Convert a (3,3,2) array into (9,2).

What does reshape(1, -1) do?

Explain the use of np.newaxis in reshaping.

Reshape an array using np.reshape().

Find the shape of an array after reshaping.

### 🟢 Reshaping Questions

### 🔵 Manipulation Questions

Add a new row to a NumPy array.

Add a new column to a NumPy array.

Remove a specific row from a NumPy array.

Remove a specific column from a NumPy array.

Insert a value at a specific index.

Insert a row into a 2D array.

Insert a column into a 2D array.

Append values to a NumPy array.

Stack two arrays vertically.

Stack two arrays horizontally.

Use vstack() to combine arrays.

Use hstack() to combine arrays.

Use concatenate() along axis 0.

Use concatenate() along axis 1.

Split an array into two equal parts.

Split an array into multiple sub-arrays.

Use hsplit() on a 2D array.

Use vsplit() on a 2D array.

Copy an array using copy().

Explain the difference between copy() and view().

Sort an array along rows.

Sort an array along columns.

Change the data type of an array.

Swap rows in a 2D array.

Swap columns in a 2D array.

Transpose a 2D array.

Transpose a 3D array.

Resize an array using resize().

Repeat elements of an array.

Tile an array multiple times.

# 🔹 Handling Missing Values in NumPy

👉 Simple & Practical Questions

Create a NumPy array containing `np.nan`.

Print an array that has missing values.

Check missing values using `np.isnan()`.

Count missing values in a 1D array.

Replace one value in an array with `np.nan`.

Check if an array contains any `np.nan`.

Find index positions of `np.nan`.

Convert a list with `None` into a NumPy array with `np.nan`.

Check datatype of an array containing `np.nan`.

Compare two `np.nan` values.

Replace `np.nan` with `0`.

Replace `np.nan` with `-1`.

Replace `np.nan` with mean value.

Remove `np.nan` from a 1D array.

Print array after removing missing values.

# 🔵 2D Array Based

Create a 2D NumPy array with missing values.

Check missing values in a 2D array.

Count missing values in each row.

Count missing values in each column.

Find rows that contain np.nan.

Find columns that contain np.nan.

Replace all missing values in a 2D array with 0.

Replace missing values column-wise.

Remove rows having missing values.

Remove columns having missing values.

Extract only rows without missing values.

Extract only columns without missing values.

Replace missing values using boolean indexing.

Use np.nan_to_num() on a 2D array.

Print array after handling missing values.

Calculate sum of array ignoring missing values.

Calculate mean ignoring missing values.

Find max value ignoring missing values.

Find min value ignoring missing values.

Replace missing values with column mean.

Replace missing values with row mean.

Check difference between mean() and nanmean().

Print output of np.nanmean().

Print output of np.nansum().

Check how np.nan affects calculation.