In [1]:
import numpy as np

1. Create a 1D array with numbers from 0 to 9.

In [4]:
arr = np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]


2. Create a 1D array with numbers from 10 to 20.

In [5]:
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


3. Convert the list [5, 10, 15, 20] into a Numpy array.

In [7]:
list = [5, 10, 15, 20]
arr = np.array(list)
print(arr)

[ 5 10 15 20]


4. Create a 1D array of 5 zeros.

In [10]:
a = np.zeros(5,)
print(a)

[0. 0. 0. 0. 0.]


5. Create a 1D array of 5 ones.

In [12]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


6. Create a 1D array of 10 evenly spaced numbers between 0 and 1.

In [18]:
# Use linespace
arr =  np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


7. Create a 1D array of 10 evenly spaced numbers between 1 and 5.

In [17]:
arr = np.linspace(1, 5, 10)
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


8. Create a 1D array of 5 random integers between 1 and 50.

In [28]:
arr = np.random.randint(1, 51, 5)
print(arr)

[13 41 21  4 46]


9. Create a 1D array of 5 random numbers between 0 and 1.

In [30]:
arr = np.random.rand(5)
print(arr)

[0.85514287 0.73858385 0.06127104 0.70093668 0.29590587]


10. Create a 1D array of numbers from 0 to 9 with a step of 2.

In [31]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


11. Create a 2x2 matrix of zeros.

In [32]:
arr = np.zeros((2, 2))
print(arr)

[[0. 0.]
 [0. 0.]]


12. Create a 3x3 matrix of ones.

In [33]:
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


13. Create a 4x4 identity matrix.

In [35]:
arr = np.eye(4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


14. Reshape 1D array [0,1,2,3,4,5,6,7,8] into 3x3 matrix.

In [36]:
arr = np.array([0,1,2,3,4,5,6,7,8])
matrix = arr.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


15. Create a 2x5 matrix using linspace() from 0 to 10.

In [37]:
arr = np.linspace(0, 10, 10)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 0.          1.11111111  2.22222222  3.33333333  4.44444444]
 [ 5.55555556  6.66666667  7.77777778  8.88888889 10.        ]]


16. Create a 1D array of 10 even numbers starting from 0.

In [39]:
arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


17. Create a 1D array of 10 odd numbers starting from 1.

In [40]:
arr = np.arange(1,21,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


18. Create a 3x3 matrix using arange() with numbers 0 to 8.

In [41]:
arr = np.arange(0, 9)
matrix = arr.reshape(3, 3)
print(arr)

[0 1 2 3 4 5 6 7 8]


19. Create a 3x2 matrix of random numbers between 0 and 1.

In [42]:
arr = np.random.rand(3, 2)
print(arr)

[[0.56347215 0.50941404]
 [0.63990693 0.88698418]
 [0.02504697 0.89785676]]


20. Create a 2x4 matrix with all elements as 7.

In [44]:
arr = np.full((2, 4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]]


21. Create a 3x3 matrix from list [[1,2,3],[4,5,6],[7,8,9]] using

In [45]:
list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list)
matrix = arr.reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
