### import numpy

In [4]:
import numpy as np

1. Create a NumPy array: [1, 2, 3, 4, 5]

In [5]:
a = [1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

2. Create an array: [10, 20, 30, 40]

In [8]:
a = [10, 20, 30, 40]
arr = np.array(a)
arr

array([10, 20, 30, 40])

3. Use arange() to create numbers from 0 to 9

In [9]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4. Use arange() from 5 to 15

In [10]:
arr = np.arange(5,15)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

5. Use arange() from 0 to 20 with step 2

In [12]:
arr = np.arange(0, 21, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

6. Create an array of odd numbers from 1 to 50

In [14]:
arr = np.arange(1, 51, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

7. Create an array from 0 to 100 with step 10

In [19]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

8. Use linspace() to generate 5 values between 0 and 1

In [18]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

9. Use linspace() to generate 10 values between 1 and 10

In [ ]:
arr = np.linspace(0,10,10)
arr

10. Create an array of 5 float values

In [20]:
arr = np.linspace(0.5, 5.5, 5)
arr

array([0.5 , 1.75, 3.  , 4.25, 5.5 ])

11. Create an array of 10 zeros

In [21]:
a = 10
arr = np.zeros(a)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

12. Create an array of 8 ones

In [24]:
s = 8
arr = np.ones(s)
arr

array([1., 1., 1., 1., 1., 1., 1., 1.])

13. Create an array of 6 elements, all equal to 7

In [26]:
arr = np.full((6),7)
arr

array([7, 7, 7, 7, 7, 7])

14. Create a 3×3 identity matrix

In [27]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

15. Create a 4×4 zero matrix

In [29]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

16. Create a 3×5 ones matrix

In [30]:
arr = np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

17. Create numbers from 1 to 100 using arange()

In [32]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

18. Reshape that array into a 10×10 matrix

In [33]:
s = np.arange(100)
arr = s.reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

19. Use linspace() to generate 25 values from 0 to 50

In [36]:
s = np.linspace(0, 50, 25)
s

array([ 0.        ,  2.08333333,  4.16666667,  6.25      ,  8.33333333,
       10.41666667, 12.5       , 14.58333333, 16.66666667, 18.75      ,
       20.83333333, 22.91666667, 25.        , 27.08333333, 29.16666667,
       31.25      , 33.33333333, 35.41666667, 37.5       , 39.58333333,
       41.66666667, 43.75      , 45.83333333, 47.91666667, 50.        ])

20. Manually create a 3×3 2D array

In [37]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

21. Create array 1–20 and extract only even numbers

In [38]:
arr = np.arange(1,21)
even = arr[arr % 2 == 0]
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

22. Create array 1–20 and extract only odd numbers

In [39]:
arr = np.arange(1, 21)
odd = arr[arr % 2 != 0]
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

23. Create an array of 10 random integers (0–100)

In [41]:
arr = np.random.randint(0, 100, 10)
arr

array([51, 18, 97,  6,  5, 45, 75,  5, 88, 44], dtype=int32)

24. Create a random 3×3 matrix

In [42]:
arr = np.random.randint(0, 101,(3,3))
arr

array([[80, 40, 43],
       [56,  4, 20],
       [58, 27, 11]], dtype=int32)

25. Create 5 random float values (0–1)

In [44]:
arr = np.random.rand(5)
arr

array([0.646821  , 0.89735601, 0.99389367, 0.71198723, 0.33624689])

26. Create array 1–50 and reverse it

In [47]:
arr = np.arange(1, 51)
s = arr[::-1]
s

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

27. Create an array of squares from 1 to 10

In [50]:
arr = np.arange(1, 11)
s = arr**2
s

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

28. Create an array of cubes from 1 to 10

In [52]:
arr = np.arange(1, 11)
s = arr**3
s

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

29. Create array 1–100 and reshape to 5×20

In [55]:
s = np.arange(1, 101)
arr = s.reshape(5, 20)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

30. Create an array of size 10 with alternating 0 and 1

In [57]:
arr = np.arange(10) % 2
arr

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# SHAPE & DIMENSIONS
1. Create a 1D array and print its shape
2. Create a 2D array (2×3) and print its shape
3. Find ndim of [1,2,3,4]
4. Find ndim of a 3×3 matrix
5. Create a 4×2 array and check shape
6. Create a 5-element array and check dimensions
7. Convert a list into NumPy array and print shape
8. Create a 2×2 matrix and print both shape and ndim
9. Create a 3×1 array
10. Create a 1×5 array

11. Reshape a 1D array (9 elements) into 3×3
12. Reshape a 1D array (6 elements) into 2×3
13. Convert 2×3 array into 3×2
14. Find total number of elements using size
15. Create a 3D array and check ndim
16. Create a 2×2×2 array
17. Flatten a 2D array into 1D
18. Convert 4×4 matrix into 1D array
19. Reshape 1D array into 1×n format
20. Check difference between shape and ndim using example

21. Reshape 1–12 array into all possible valid shapes
22. Create a 3D array and extract its shape
23. Convert 3×4 into 4×3 and compare results
24. Flatten a 3×3 matrix and reshape into 1×9
25. Create array and dynamically reshape using variable
26. Check if reshape changes data or just structure
27. Create mismatched reshape case and observe error
28. Convert 1D → 3D → 1D again
29. Find shape after slicing a 2D array
30. Create array and verify relationship between shape, size, ndim

# INDEXING & SLICING
1. Create array [10, 20, 30, 40, 50] and print first element
2. Print last element of array [1,2,3,4,5]
3. Print 3rd element from array
4. Slice first 3 elements from [5,10,15,20,25]
5. Slice last 2 elements
6. Print elements from index 1 to 3
7. Reverse array [1,2,3,4,5]
8. Get every second element from array
9. Create array and print middle element
10. Print elements from index 2 to end

11. Create 2D array (3×3) and print first row
12. Print second row of a 2D array
13. Print first column of a 2D array
14. Print last column of a 2D array
15. Access element at (2,3) in matrix
16. Slice sub-matrix (first 2 rows, first 2 columns)
17. Extract last row of matrix
18. Extract middle element from 3×3 matrix
19. Replace first row with zeros
20. Replace a column with 1s

21. Create 4×4 matrix and extract diagonal elements
22. Extract anti-diagonal elements
23. Flatten matrix using slicing
24. Replace elements > 50 with 0
25. Extract only even numbers from array using slicing/filtering
26. Modify middle row of matrix
27. Swap first and last row of matrix
28. Swap two columns
29. Extract a 2×2 block from center of matrix
30. Combine slicing + indexing to extract custom pattern

# BROADCASTING
Add 5 to array [1,2,3,4,5]
Multiply array [1,2,3] by 2
Subtract 10 from each element
Add [1,1,1] to [10,20,30]
Divide array by 2
Add scalar 100 to array [5,10,15]
Multiply array by 0
Add 3 to every element in range 1–10
Square each element using broadcasting
Subtract array from scalar 50

Add [1,2,3] to each row of a 3×3 matrix
Add column vector to 2D matrix
Multiply each row by [1,2,3]
Add [10,20,30] to 3×3 matrix
Subtract row-wise vector from matrix
Divide each column by [1,2,3]
Add scalar to 2D matrix
Multiply matrix by row vector
Broadcast 1D array into 2D addition
Check result of shape mismatch addition

Add row vector to matrix without loops
Add column vector to matrix
Multiply each column differently using broadcasting
Create custom scaling per row
Normalize matrix using broadcasting
Subtract mean of each row (row-wise normalization)
Subtract mean of each column
Standardize matrix (mean = 0 style)
Create matrix + vector combination operation
Explain why broadcasting works in a 3×1 + 1×3 case (code it)

## BASIC OPERATIONS (SUM, MEAN, MAX)
Find sum of [1,2,3,4,5]
Find mean of [10,20,30,40]
Find max value in [5,15,25,35]
Find min value in [3,6,9,12]
Find sum of array [2,4,6,8]
Find average of [1,3,5,7,9]
Find max of [100,200,50]
Find min of [90,80,70]
Add all elements in array [11,22,33]
Compute mean of [5,10,15,20,25]

Find row-wise sum of 3×3 matrix
Find column-wise mean of matrix
Find max of each row
Find min of each column
Sum all elements in 2D array
Compute average of each row
Find index of maximum value (argmax)
Find index of minimum value (argmin)
Compare sum of two arrays
Find difference between max and min

Find sum of even numbers in array
Find sum of odd numbers in array
Find mean of only elements > 50
Find max in each row and column
Normalize array using mean
Standard deviation idea (basic level)
Compare two matrices using sum
Find row with highest sum
Find column with lowest mean
Apply sum, mean, max on same dataset and interpret result