# What is Random in NumPy
- The `numpy.random` module is used to generate random numbers or arrays.

- Can create random floats, integers, normal distributions, or random selections.

### Examples:

1. Random floats [0,1)
- Generates random floating-point numbers in the range 0 (inclusive) to 1 (exclusive).

- NumPy, use `np.random.rand()`.

In [1]:
import numpy as np
arr = np.random.rand(5)
print(arr)

[0.45111143 0.36514246 0.88918144 0.50108543 0.6612163 ]


2. Random integers
- Generates random integer numbers within a specified range.

- use np.random.randint(low, high, size).

### Syntax
`np.random.randint(low, high, size)`
- low → minimum integer (inclusive)
- high → maximum integer (exclusive)
- size → number of integers to generate

In [11]:
arr = np.random.randint(1, 10, size=5)  # 5 random integers between 1 and 9
print(arr)


[1 8 5 7 3]


In [2]:
arr = np.random.randint(1, 10, size=5)
print(arr)

[8 5 7 1 3]


3. Random from normal distribution
- Generates random numbers that follow a normal (Gaussian) distribution.

- Normal distribution = bell-shaped curve with mean = 0 and standard deviation = 1 by default.

In [3]:
arr = np.random.randn(5)
print(arr)

[-1.3998511  -1.131773   -1.22329192  0.11489781 -2.59961751]


4. Random choice from a list
- `np.random.choice()` selects one or more random elements from a given list or array.

In [8]:
arr = np.random.choice([10, 20, 30, 40], size=3)
print(arr)

[20 40 30]
