Q1. Create array [1,2,3,4,5] and find sum.

Q2. Find mean of [10,20,30,40].

Q3. Find max & min of [8,3,15,2,9].

Q4. Multiply [1,2,3] by 10.

Q5. Add [1,2,3] and [4,5,6].

Q6. Subtract [5,6,7] from [10,20,30].

Q7. Divide [10,20,30] by 10.

Q8. Find square of [2,4,6].

Q9. Find cube of [1,2,3].

Q10. Find average of [5,10,15,20,25].

In [1]:
import numpy as np

In [3]:
arr = [1, 2, 3, 4, 5]
s = np.array(arr)
s.sum()

np.int64(15)

In [4]:
arr = arr = [10, 20, 30, 40]
s = np.array(arr)
s.mean()

np.float64(25.0)

In [6]:
arr = [8,3,15,2,9]
s = np.array(arr)
s.max(),s.min()

(np.int64(15), np.int64(2))

In [7]:
arr = [1, 2, 3]
s = np.array(arr)
s*10

array([10, 20, 30])

In [9]:
a = [1, 2, 3]
b = [4, 5, 6]
ar = np.array(a)
arr = np.array(b)
ar + arr

array([5, 7, 9])

In [10]:
a = [5, 6, 7]
b = [10, 20, 30]
ar = np.array(a)
arr = np.array(b)
arr - ar

array([ 5, 14, 23])

In [11]:
a = [10, 20, 30]
arr = np.array(a)
arr / 10

array([1., 2., 3.])

In [13]:
a = [2, 4, 6]
arr = np.array(a)
arr**2

array([ 4, 16, 36])

In [14]:
a = [1, 2, 3]
arr = np.array(a)
arr**3

array([ 1,  8, 27])

In [15]:
a = [5,10,15,20,25]
arr = np.array(a)
arr.mean()

np.float64(15.0)

Q11. Create 2D array:
[[1,2,3],
 [4,5,6],
 [7,8,9]]

Find total sum.

In [19]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
arr = np.array(a)
arr.sum()

np.int64(45)

Q12. Find row-wise sum.

In [ ]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
arr = np.array(a)
print(arr.sum(axis=1))

[ 6 15 24]


Q13. Find column-wise sum.

In [23]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
arr = np.array(a)
print(arr.sum(axis=0))

[12 15 18]


Q14. Find mean of each row.

In [24]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
arr = np.array(a)
print(arr.mean(axis=1))

[2. 5. 8.]


Q15. Find max value in each column.

In [25]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
arr = np.array(a)
print(arr.max(axis=0))

[7 8 9]


Q16. Broadcasting:
[1,2,3] + 5

In [37]:
a = [1, 2, 3]
arr = np.array(a)
arr + 5

array([6, 7, 8])

Q17. Multiply:
[1,2,3] * [4,5,6]

In [38]:
a = [1, 2, 3]
ar = np.array(a)
b = [4, 5, 6]
arr = np.array(b)
ar * arr

array([ 4, 10, 18])

Q18. Find standard deviation:
[10,20,30,40,50]

In [27]:
a = [10, 20, 30, 40, 50]
arr = np.array(a)
arr.std()

np.float64(14.142135623730951)

Q19. Normalize:
[10,20,30,40]

In [30]:
a = [10, 20, 30, 40]
arr = np.array(a)
norm = (arr - arr.min()) / (arr.max() - arr.min())
norm

array([0.        , 0.33333333, 0.66666667, 1.        ])

Q20. Replace values > 25 with 0:
[10,30,20,40,15]

In [31]:
a = [10,30,20,40,15]
arr = np.array(a)
arr[arr>25] = 1
arr

array([10,  1, 20,  1, 15])

Q21. Dot product:
[1,2,3] • [4,5,6]

In [40]:
a = (np.dot([1, 2, 3],[4, 5, 6]))
a

np.int64(32)

Q22. Matrix multiplication:
A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

In [41]:
a = [[1,2],
     [3,4]]
b = [[5,6],
     [7,8]]
ar = np.array(a)
arr = np.array(b)
ar @ arr

array([[19, 22],
       [43, 50]])

Q23. Find cumulative sum:
[1,2,3,4,5]

In [42]:
a = [1,2,3,4,5]
arr = np.cumsum(a)
arr

array([ 1,  3,  6, 10, 15])

Q24. Find cumulative product:
[1,2,3,4]

Q25. Find indices where value > 20:
[10,25,30,15,5]

Q26. Clip values between 10 and 20:
[5,12,25,8,30]

Q27. Replace even numbers with 0:
[1,2,3,4,5,6]

Q28. Find unique values:
[1,2,2,3,4,4,5]

Q29. Sort array descending:
[10,5,20,15]

Q30. Find correlation between:
x = [1,2,3,4]
y = [2,4,6,8]

In [36]:
x = [1,2,3,4]
y = [2,4,6,8]
ar = np.array(x)
arr = np.array(y)
print(np.corrcoef(ar,arr))

[[1. 1.]
 [1. 1.]]
